deploy2:v7

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,8 +36,7 @@ jobs:
           sleep 30  # Allow MySQL to fully initialize
 
       - name: Verify MySQL is Running
-        run: |
-          docker exec mysql-db mysqladmin ping -h mysql-db -u root -pmysecurepassword
+        run: docker exec mysql-db mysqladmin ping -h mysql-db -u root -pmysecurepassword
 
       - name: Build PHP Apache Docker Image
         run: |
@@ -47,7 +46,9 @@ jobs:
       - name: Run PHP Apache Container
         run: |
           echo "Starting PHP Apache container..."
-          docker run -d --name php-apache-app --network mynetwork -p 80:80 php-apache-app || { echo "Failed to start php-apache-app container"; exit 1; }
+          docker run -d --name php-apache-app \
+            --network mynetwork \
+            -p 80:80 php-apache-app || { echo "Failed to start php-apache-app container"; exit 1; }
 
       - name: Verify Running Containers
         run: docker ps -a
